harnessApiVersion: '1.0'
type: PROMETHEUS
alertEnabled: false
alertThreshold: 0.5
analysisTolerance: LOW
connectorName: student24-sw-monitoring
enabled24x7: true
numOfOccurrencesForAlert: 1
serviceName: cvdeploy
timeSeriesList:
- metricName: normal_call
  metricType: THROUGHPUT
  txnName: custom
  url: io_harness_custom_metric_normal_call{kubernetes_pod_name="$hostName"}
- metricName: error_call
  metricType: ERROR
  txnName: custom
  url: io_harness_custom_metric_error_call{kubernetes_pod_name="$hostName"}
